publisher:
  name: Solana Mobile
  address: ''
  website: https://solanamobile.com
  email: hello@solanamobile.com
  media:
    - purpose: icon
      uri: ./media/publisher_icon.jpeg
app:
  name: Cute Kittens
  address: ''
  android_package: com.solanamobile.cutekittens
  urls:
    license_url: https://cdn.org/license.html
    copyright_url: https://cdn.org/copyright.html
    privacy_policy_url: https://cdn.org/privacy.html
    website: https://solanamobile.com
  media:
    - purpose: icon
      uri: ./media/app_icon.jpeg
release:
  address: ''
  media:
    - purpose: icon
      uri: ./media/release_icon.png
    - purpose: screenshot
      uri: ./media/app_screenshot.png
    - purpose: screenshot
      uri: ./media/app_screenshot1.png
    - purpose: screenshot
      uri: ./media/app_screenshot2.png
    - purpose: screenshot
      uri: ./media/app_screenshot3.png
    - purpose: screenshot
      uri: ./media/app_screenshot4.png
  files:
    - purpose: install
      uri: ./files/app-debug.apk
  catalog:
    en-US:
      name: This is a single release
      short_description: A short description
      long_description: Some wonderful release notes, in long-form
      new_in_version: Something new in this version
      saga_features: Some information about saga specific features
solana_mobile_dapp_publisher_portal:
  google_store_package: com.company.dapp.otherpkg
  testing_instructions: Here are some steps informing Solana Mobile of how to test this dapp. You can specify multiple lines of instructions. For example, if a login is needed, you would add those details here.
