publisher:
  name: My new publisher name
  address: BrWNieTsfdkkwMaz2A616i1fkqSjxk2kHhTn1Y44pi48
  website: https://solanamobile.com
  email: hello@solanamobile.com
  media:
    - purpose: icon
      uri: ./media/publisher_icon.jpeg
      width: 512
      height: 512
app:
  name: My new app name
  address: 4xE4MDVHfFAXMKKzqrJ2v1HxcgYgdoV98nuvd8SRKhWP
  android_package: com.company.dapp
  creators:
    - 7pF18kRbv4mWdLPNMa8CjqLotQpznxzzRJqwdMibMitE
  urls:
    license_url: http://cdn.org/license.html
    copyright_url: http://cdn.org/copyright.html
    privacy_policy_url: http://cdn.org/privacy.html
    website: http://cdn.org
  media:
    - purpose: icon
      uri: ./media/app_icon.jpeg
      width: 512
      height: 512
release:
  version: 1.0.4
  address: HeXP8pLxxzWPo1j7FwsytrCBN9Q7HZ3MA8TVCVGj5eCA
  media:
    - purpose: screenshot
      uri: ./media/app_screenshot.png
      width: 512
      height: 512
  files:
    - purpose: install
      uri: ./files/app-debug.apk
  catalog:
    en-US:
      name: |
        A nice, helpful dApp name
      short_description: |
        Some wonderful release notes
      long_description: |
        Some wonderful release notes, in long-form
      new_in_version: |
        Something new in this version
      saga_features_localized: |
        Some information about saga specific features
solana_mobile_dapp_publisher_portal:
  google_store_package: com.company.dapp.otherpkg
  testing_instructions: >
    Here are some steps informing Solana Mobile of how to test this dapp. You
    can specify multiple lines of instructions. For example, if a login is
    needed, you would add those details here.
